### ISSUE TITLE
After creating fieldset its not possible to add fields to it.

### ISSUE THREAD

**Issue by jensens** [plone/plone.schemaeditor#30]
1. Create fieldset using the UI
2. Click on fieldset.
3. Click add field

-> Field is created at default fieldset

Also I do not see any option to move a field to a fieldset.

**Comment by cdw9** [comment]
This fix does not appear to be working. Testing version 2.0.19 on Plone 5.0.6 - I can drag and drop fields to other fieldsets, but the change doesn't stick. When I leave and return to the Fields tab, the field is back on the Default tab.

**Comment by petschki** [comment]
I've opened a new Issue for the field moving. See #65
