### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by MareoRaft** [plone/plone.schemaeditor#52]
This is a feature request.  Could you provide a link to a demo in your README?  I would like to see your project before investing time in trying it out myself.

**Comment by gforcada** [comment]
@MareoRaft if you are looking for demo sites of Plone CMS you can get a list of them at https://plone.com especifically at https://plone.com/try-plone

A high level overview of Plone's features can be seen here: https://plone.com/features

**Comment by MareoRaft** [comment]
Thanks, this is great.  You may consider putting this in your README.  Good luck with everything.
