### ISSUE TITLE
Cannot edit or delete fieldset

### ISSUE THREAD

**Issue by reinhardt** [plone/plone.schemaeditor#69]
After adding a fieldset I noticed a typo in its title, so I wanted to edit it, but I couldn't find an "Edit" button or a view that allows me to modify it. Neither does it seem possible to delete the fieldset (and create a new one without the typo). Both is of course possible by modifying the schema XML, but there don't seem to be UI elements for either editing or deleting field sets.

I tried on Plone 5.1b3 with plone.schemaeditor 2.0.18, both using collective.easyform 2.1.0 and dexterity TTW editing (plone.app.dexterity 2.4.1).

**Comment by reinhardt** [comment]
I'm working on a PR that adds a delete button.

**Comment by avoinea** [comment]
I think this can be safely closed @mauritsvanrees
