### ISSUE TITLE
SchemaCache is not updated across multiple Plone instances

### ISSUE THREAD

**Issue by avoinea** [plone/plone.schemaeditor#81]
**How to reproduce:**

1. Start a ZEO cluster with 2 Plone ZEO clients
2. Add Plone Site
3. Go to first Plone instance > Site Setup > Dexterity Content-Types > Page
4. Add new fieldset and new text field and press "Done"
5. Go to the second Plone instance > Site Setup > Dexterity Content-Types > Page
6. Notice the missing custom **fieldset / field**

Plone version: 5.2.2

See also: https://community.plone.org/t/dynamic-schema-is-not-synced-across-zeo-clients/12923

**Comment by avoinea** [comment]
SCHEMA_CACHE https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/schema.py#L277

**Comment by avoinea** [comment]
EditableSchema https://github.com/plone/plone.schemaeditor/blob/master/plone/schemaeditor/utils.py#L89

**Comment by jensens** [comment]
So, the schema cache is not invalidated on the other client?

**Comment by avoinea** [comment]
@jensens Indeed. I did some digging and now I'm not that sure that the issue is generated by SCHEMA_CACHE.

**Comment by jensens** [comment]
You may write a simple view that invalidates the schema cache - and if it works afterwards it is the cache ;)

**Comment by avoinea** [comment]
> You may write a simple view that invalidates the schema cache - and if it works afterwards it is the cache ;)

I commented the caching part in [volatile](https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/schema.py#L102) and the issue is still there.

That's why I suspect the issue is in [EditableSchema](https://github.com/plone/plone.schemaeditor/blob/master/plone/schemaeditor/utils.py#L85)

Thus, when you add a new field, it is directly added in the schema `_InterfaceClass__attrs` and then [serialized](https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/serialize.py#L9) and saved to portal_types as `model_source` XML. But this value is never deserialized on get (only on Zope start). 

I still don't have the whole picture, thus I may be wrong on that.

**Comment by avoinea** [comment]
[ftiModified](https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/fti.py#L506) is supposed to re-sync schema, but:
1. [ObjectModified](https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/configure.zcml) is not triggered on schema edit (add field, add fieldset, save defaults)
2. This wouldn't fix our issue as the event is triggered only on the ZEO client where the action took place.

We need to re-sync schema from model_source on get (based on fti modification time, or something). See also https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/schema.py#L409-L410. This code is executed only once per ZEO client, when you first access that schema.

**Comment by avoinea** [comment]
Yap. Removing https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/schema.py#L409-L415 solved the issue.

My proposal is to also add `fti._p_time` to this `_transient_SCHEMA_CACHE`. 

Any other suggestions are welcomed.

**Comment by avoinea** [comment]
See https://github.com/plone/plone.dexterity/issues/136
